### PR TITLE
Order commutes with newest on top

### LINKED ISSUE #14: List view should be ordered with newest commutes first so the active commute is always on top
Currently it’s in ascending order by date, which is annoying when you have enough commutes to fill the screen as the active commute is not visible until you scroll.

### PR DESCRIPTION
**Pull request by toastersocks**
Resolve #14
I'm not sure how this might work with #13 (What if morning commutes are in section 0 but the newest commute is an evening commute? Does it appear at the top of the evening commute section? Or maybe they are ordered within their own sections, but the active commute appears at the very top in its own section)

### CODE REVIEW

**Comment by aranasaurus** [comment]
That’s also a great point about the active commute for #13. My initial thought is that it’d just be the first commute in whichever section it goes in. But maybe a separate section (or even separate control altogether, like a Label all by itself) would be better. I’ll have to think on that a bit.

**Comment by toastersocks** [comment]
Oh, yeah good point about it being confusing to have the VC arbitrarily reversing any array that gets passed in.

**Comment by toastersocks** [comment]
Ok, I think I have it all "sorted" out. 😬
Doing an explicit sort in the `AppManager` before passing into the VC.

**Comment by aranasaurus** [comment]
👌! Also 🙌 for the pun 😂

**Pull request merged**
